version: "3"

vars:
  TINY_FLAGS: "-target wasi -no-debug -tags=purego  -scheduler=none"


tasks:
  default:
    cmds:
      - task: build_all
  clean:
    desc: Clear output directory
    cmds:
      - rm -fr plugins
  init:
    desc: create output directory
    cmds:
      - mkdir plugins || echo "plugins directory already exists"
  cipher_ansible:
    desc: "Build ansible vault plugin "
    cmds:
      - tinygo build -o plugins/cipher_ansible.wasm {{ .TINY_FLAGS }}  cipher/ansible/plugin.go
  cipher_aes:
    desc: "Build aes-256-gcm vault plugin "
    cmds:
      - tinygo build -o plugins/cipher_aes256_gcm.wasm {{ .TINY_FLAGS }}  cipher/aes-256-gcm/plugin.go
  run_tests:
    desc: "Build ansible vault plugin "
    cmds:
      - go test -v ./...
    deps:
      - task: build_all
  build_all:
    desc: "Building All binaries"
    cmds:
      - task: cipher_ansible
      - task: cipher_aes
    deps:
      - task: clean
      - task: init
